-- MySQL Script generated by MySQL Workbench
-- 03/21/17 19:19:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EstadoDelSuscriptor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EstadoDelSuscriptor` (
  `idEstadoDelSuscriptor` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstadoDelSuscriptor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `NombreUsuario` VARCHAR(45) NULL,
  `ApellidoUsuario` VARCHAR(45) NULL,
  `CorreoPersonal` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `EstadoDelSuscriptor_idEstadoDelSuscriptor` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_EstadoDelSuscriptor1_idx` (`EstadoDelSuscriptor_idEstadoDelSuscriptor` ASC),
  CONSTRAINT `fk_Usuario_EstadoDelSuscriptor1`
    FOREIGN KEY (`EstadoDelSuscriptor_idEstadoDelSuscriptor`)
    REFERENCES `mydb`.`EstadoDelSuscriptor` (`idEstadoDelSuscriptor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Editorial` (
  `idEditorial` INT NOT NULL AUTO_INCREMENT,
  `NombreEditorial` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`idEditorial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstadoPrestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EstadoPrestamo` (
  `idEstadoPrestamo` INT NOT NULL AUTO_INCREMENT,
  `DescripciondelEstado` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstadoPrestamo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TiempoLimitePrestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TiempoLimitePrestamo` (
  `idTiempoPrestamo` INT NOT NULL AUTO_INCREMENT,
  `Dias` DATETIME NULL,
  PRIMARY KEY (`idTiempoPrestamo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstadoConservacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EstadoConservacion` (
  `idEstadoDeConservacion` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstadoDeConservacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Libro` (
  `idLibros` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NULL,
  `Edicion` VARCHAR(45) NULL,
  `FechaPublicacion` INT NULL,
  `DescripcionFisica` VARCHAR(45) NULL,
  `RegistroLibro` VARCHAR(45) NULL,
  `Genero` VARCHAR(45) NULL,
  `Editorial_idEditorial` INT NOT NULL,
  `EstadoPrestamo_idEstadoPrestamo` INT NOT NULL,
  `TiempoLimitePrestamo_idTiempoPrestamo` INT NOT NULL,
  `EstadoConservacion_idEstadoDeConservacion` INT NOT NULL,
  PRIMARY KEY (`idLibros`),
  INDEX `fk_Libro_Editorial1_idx` (`Editorial_idEditorial` ASC),
  INDEX `fk_Libro_EstadoPrestamo1_idx` (`EstadoPrestamo_idEstadoPrestamo` ASC),
  INDEX `fk_Libro_TiempoLimitePrestamo1_idx` (`TiempoLimitePrestamo_idTiempoPrestamo` ASC),
  INDEX `fk_Libro_EstadoConservacion1_idx` (`EstadoConservacion_idEstadoDeConservacion` ASC),
  CONSTRAINT `fk_Libro_Editorial1`
    FOREIGN KEY (`Editorial_idEditorial`)
    REFERENCES `mydb`.`Editorial` (`idEditorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_EstadoPrestamo1`
    FOREIGN KEY (`EstadoPrestamo_idEstadoPrestamo`)
    REFERENCES `mydb`.`EstadoPrestamo` (`idEstadoPrestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_TiempoLimitePrestamo1`
    FOREIGN KEY (`TiempoLimitePrestamo_idTiempoPrestamo`)
    REFERENCES `mydb`.`TiempoLimitePrestamo` (`idTiempoPrestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_EstadoConservacion1`
    FOREIGN KEY (`EstadoConservacion_idEstadoDeConservacion`)
    REFERENCES `mydb`.`EstadoConservacion` (`idEstadoDeConservacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bibliotecario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bibliotecario` (
  `idbibliotecario` INT NOT NULL AUTO_INCREMENT,
  `nombrebibliotecario` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`idbibliotecario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FichaDePrestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FichaDePrestamo` (
  `idFichaDePrestamo` INT NOT NULL AUTO_INCREMENT,
  `FechaDeEntrega` DATETIME NULL,
  `FechaDedevolucion` DATETIME NULL,
  `CantidadDelibros` INT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Bibliotecario_idbibliotecario` INT NOT NULL,
  PRIMARY KEY (`idFichaDePrestamo`),
  INDEX `fk_FichaDePrestamo_Usuario1_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_FichaDePrestamo_Bibliotecario1_idx` (`Bibliotecario_idbibliotecario` ASC),
  CONSTRAINT `fk_FichaDePrestamo_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FichaDePrestamo_Bibliotecario1`
    FOREIGN KEY (`Bibliotecario_idbibliotecario`)
    REFERENCES `mydb`.`Bibliotecario` (`idbibliotecario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DetallePrestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DetallePrestamo` (
  `Libro_idLibros` INT NOT NULL,
  `FichaDePrestamo_idFichaDePrestamo` INT NOT NULL,
  PRIMARY KEY (`Libro_idLibros`, `FichaDePrestamo_idFichaDePrestamo`),
  INDEX `fk_Libro_has_FichaDePrestamo_FichaDePrestamo1_idx` (`FichaDePrestamo_idFichaDePrestamo` ASC),
  INDEX `fk_Libro_has_FichaDePrestamo_Libro1_idx` (`Libro_idLibros` ASC),
  CONSTRAINT `fk_Libro_has_FichaDePrestamo_Libro1`
    FOREIGN KEY (`Libro_idLibros`)
    REFERENCES `mydb`.`Libro` (`idLibros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_has_FichaDePrestamo_FichaDePrestamo1`
    FOREIGN KEY (`FichaDePrestamo_idFichaDePrestamo`)
    REFERENCES `mydb`.`FichaDePrestamo` (`idFichaDePrestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Bibliotecario_idbibliotecario` INT NOT NULL,
  PRIMARY KEY (`idLogin`),
  INDEX `fk_Login_Usuario1_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Login_Bibliotecario1_idx` (`Bibliotecario_idbibliotecario` ASC),
  CONSTRAINT `fk_Login_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Login_Bibliotecario1`
    FOREIGN KEY (`Bibliotecario_idbibliotecario`)
    REFERENCES `mydb`.`Bibliotecario` (`idbibliotecario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ConsultaLibro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ConsultaLibro` (
  `idConsultaLibro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `Autor` VARCHAR(45) NULL,
  `Genero` VARCHAR(45) NULL,
  `Editorial` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `FichaDePrestamo_idFichaDePrestamo` INT NOT NULL,
  PRIMARY KEY (`idConsultaLibro`),
  INDEX `fk_ConsultaLibro_Usuario1_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_ConsultaLibro_FichaDePrestamo1_idx` (`FichaDePrestamo_idFichaDePrestamo` ASC),
  CONSTRAINT `fk_ConsultaLibro_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConsultaLibro_FichaDePrestamo1`
    FOREIGN KEY (`FichaDePrestamo_idFichaDePrestamo`)
    REFERENCES `mydb`.`FichaDePrestamo` (`idFichaDePrestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
